import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/app/ui/header"
import Login_Form from "@/app/ui/login-form"
import Login_Sign_In from "@/app/ui/login-sign-in"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


  <Login_Form />
  <Login_Sign_In />
        <div className="flex justify-center">
          <div className="md:w-11/12 p-4">
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
